version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - todo-network

  celery:
    build: .
    command: celery -A django_todos_project worker --loglevel=info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - todo-network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - todo-network

volumes:
  redis_data:

networks:
  todo-network:
    driver: bridge